- hosts: vms
  
  tasks:
    - name: Ping servers
      ping:

    - name: Checkout the Gfx hat library repo
      git:
        repo: 'https://github.com/j0hanj0han/myGFXhat.git'
        dest: /home/pi/Projects/mygfxhat

    # - name: Apt-get update
    #   shell: sudo apt-get update
    
    # - name: Install python3
    #   shell: sudo apt-get -y install python3
    
    # - name: Install virtualenv
    #   shell: sudo apt-get -y install virtualenv

    - name: Install requirements
      pip: 
        requirements: /home/pi/Projects/mygfxhat/requirements.txt
        virtualenv: /home/pi/Projects/mygfxhat/myenv
        virtualenv_python: python2
      
    - name: virtualenv activate
      shell: . /home/pi/Projects/mygfxhat/myenv/bin/activate
    
    # - name: Launch display
    #   shell: python2 /home/pi/Projects/mygfxhat/mygfxhat/main.py

    # - name: "Activate virtual env"
    # - name: "Install dependencies"
    # - name: "Launch the program"
