- hosts: group1
  
  tasks:
    - name: Ping servers
      ping:

    - name: Checkout the Gfx hat library repo
      git:
        repo: 'https://github.com/j0hanj0han/myGFXhat.git'
        dest: /home/pi/Projects/mygfxhat

    # - name: Apt-get update
    #   shell: sudo apt-get update
    
    - name: Install virtualenv 
      shell: pip3 install virtualenv
      become: yes
      become_user: root
    
    # - name: Install virtualenv via pip
    #   pip:
    #     name: virtualenv
    #     executable: pip3
    #     become: yes
    #     become_user: root

    - name: Install requirements
      pip: 
        requirements: /home/pi/Projects/mygfxhat/requirements.txt
        virtualenv: /home/pi/Projects/mygfxhat/venv
        virtualenv_python: python3
      
    - name: virtualenv activate
      shell: source /home/pi/Projects/mygfxhat/venv/bin/activate
    
    - name: Launch display
      shell: python3 /home/pi/Projects/mygfxhat/mygfxhat/main.py

    # - name: "Activate virtual env"
    # - name: "Install dependencies"
    # - name: "Launch the program"
